all:
	g++ -c `root-config --cflags` -I/Users/Tim/PhD/RootImprover/Include/ ExplainBDT.cpp
	g++ -o ExplainBDT `root-config --glibs` -L/Users/Tim/PhD/RootImprover/lib -lMyOther -lMyRootExtras ExplainBDT.o 
